version: "3"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  gen:
    desc: Generate protobuf files and templ files
    silent: true
    cmds:
      - devbox run proto
      - devbox run templ

  run:devnet:
    desc: Start development network
    silent: true
    cmds:
      - devbox run devnet

  run:testnet:
    desc: Start test network
    silent: true
    cmds:
      - devbox run testnet

  network:up:
    aliases:
      - "net-up"
    desc: Deploy the Sonr Testnet
    silent: true
    cmds:
      - devbox services up --background --process-compose-file ./deploy/networks/testnet/process-compose.yml

  rails:up:
    aliases:
      - "rls-up"
    desc: Starts the devbox services (background)
    silent: true
    cmds:
      - devbox services up --background --process-compose-file ./deploy/rails/process-compose.yml

  services:down:
    aliases:
      - "rls-kill"
    desc: Stops the devbox services
    silent: true
    cmds:
      - devbox services down

  services:ls:
    aliases:
      - "rls-ls"
    desc: Lists the devbox services
    silent: true
    cmds:
      - devbox services ls
